E:[u:();e:{a::?[a;x;y];J(*x)+#y};cz:{$[#u;e/_`u;]};kx:{u,:,(j,j+#x;*k_a);e[k]x};kb:{$[=/k;J j-1 0;];kx""};cx:{kx cc`};cv:{kx@9'`}]
A:[w::_W%F;j::*k;k:0 0;J:{k::2#0|x&#a};lx:{J j+x};y::V+F*0,j;z::1'(V;w[1]$a)],E

U:{(`Z,'!Z).'+x};V:0;i:0;I::`Z,(!Z)(#Z)!i;y:{I .`y};zf:{$[`kt=*x;i+:1;^`W`F?*x;I . x;. x]};u::F[0]*!#Z;W:{U`V,,u,'0;U`W,,(-':1_u,*x),'x 1};z:{U`z;1'(V;U[`a]{$[#x;"";y]}'$!Z;3)}
Z:`to`cc`subj`!A$/:4#()
